[package]
name = "starship-plugins-poc"
version = "0.1.0"
authors = ["Matan Kushner <hello@matchai.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [workspace]
# members = ["crates/*/"]

[dependencies]
anyhow = "1"
futures = "0.3"
tarpc = { version = "0.26", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tokio-serde = { version = "0.8.0", features = ["bincode"] }
tokio-util = { version = "0.6.8", features = ["codec"] }

[lib]
name = "service"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "starship-plugin-directory"
path = "src/modules/directory.rs"
