[package]
name = "starship-plugin"
version = "0.1.0"
authors = ["Matan Kushner <hello@matchai.dev>"]
edition = "2018"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
